version: 2
updates:
  - package-ecosystem: composer
    directory: /api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
